version: "3.9"

services:
  forward-proxy-server:
    build:
      context: ./http-forward-proxy
      dockerfile: Dockerfile
    container_name: forward-proxy-server
    depends_on:
      - reverse-proxy-server
    networks:
      - public-net
      - internal-net
    ports:
      - "6790:6790"
    command: ["./proxy-server", "-host", "0.0.0.0", "-port", "6790"]

  reverse-proxy-server:
    build:
      context: ./http-reverse-proxy
      dockerfile: Dockerfile
    container_name: reverse-proxy-server
    depends_on:
      - http-server-1
      - http-server-2
    networks:
      - internal-net
    ports:
      - "7090:7090"
    command: ["./reverse-proxy-server", "-host", "0.0.0.0", "-port", "7090", "-map", "/server1=http-server-1:8081,/server2=http-server-2:8082"]

  http-server-1:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    container_name: http-server-1
    # ports:
    #   - "8081:8081"
    command: ["./server", "-host", "0.0.0.0", "-port", "8081"]
    restart: unless-stopped
    networks:
      - internal-net
    volumes:
      - ./http-server/index_server_1.html:/root/index.html:ro

  http-server-2:
    build:
      context: ./http-server
      dockerfile: Dockerfile
    container_name: http-server-2
    # ports:
    #   - "8081:8081"
    command: ["./server", "-host", "0.0.0.0", "-port", "8082"]
    restart: unless-stopped
    networks:
      - internal-net
    volumes:
      - ./http-server/index_server_2.html:/root/index.html:ro

networks:
  internal-net:
    driver: bridge
  public-net:
    driver: bridge