name: Build and Deploy HTTPProxySuite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Build Forward Proxy
        run: |
          cd http-forward-proxy
          go build -o proxy-server

      - name: Build Reverse Proxy
        run: |
          cd http-reverse-proxy
          go build -o reverse-proxy-server

      - name: Build HTTP Server
        run: |
          cd http-server
          go build -o server

      - name: Run Tests
        run: |
          go test ./...
